// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Url struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	PlainUrl  string
	ShortUrl  string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

type UrlAnalytic struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Referer   string
	UserAgent string
	Ip        string
	ShortUrl  string
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Name      string
	Password  string
}
