// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: url_analytics.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createURLAnalyticRecord = `-- name: CreateURLAnalyticRecord :one
INSERT INTO url_analytics (
    id,
    created_at,
    updated_at,
    referer,
    user_agent,
    ip,
    short_url
) 
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, referer, user_agent, ip, short_url
`

type CreateURLAnalyticRecordParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Referer   string
	UserAgent string
	Ip        string
	ShortUrl  string
}

func (q *Queries) CreateURLAnalyticRecord(ctx context.Context, arg CreateURLAnalyticRecordParams) (UrlAnalytic, error) {
	row := q.db.QueryRowContext(ctx, createURLAnalyticRecord,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Referer,
		arg.UserAgent,
		arg.Ip,
		arg.ShortUrl,
	)
	var i UrlAnalytic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Referer,
		&i.UserAgent,
		&i.Ip,
		&i.ShortUrl,
	)
	return i, err
}
